# Generated by Django 5.1.1 on 2024-09-28 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_remove_customuser_username"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="customuser",
            table="app_users",
        ),
    ]
