# Generated by Django 5.1.1 on 2024-11-03 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0003_alter_customuser_table"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="customuser",
            managers=[],
        ),
    ]
